<a href="https://colab.research.google.com/github/Farahnosh-Yousofi/Naive-Bayes--Perceptron--Linear-models/blob/main/MA421HW4_Question4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This Colab is to answer the 4th question of homework assignment
## How to implement a neural network using cross entropy loss function

In [28]:
# importing necessary libraries
import math #for sigmoid function
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam
%matplotlib inline

In [29]:
# getting my data
import pandas as pd

data = [[1,-2,0],[2,0,1]]
df = pd.DataFrame(data, columns = ("x1","x2","labels"))
df

x1  x2  labels
0   1  -2       0
1   2   0       1

In [30]:
# x_train and y_train
x_train = df[['x1','x2']]
x_train

x1  x2
0   1  -2
1   2   0

In [31]:
y_train= df[['labels']]
y_train

labels
0       0
1       1

# Building the model using tensorflow

In [32]:
# Developing our model for the assignment neural network model for this problem with one hidden layer (L = 1) of dimension 2 (n1 = 2). Train the neural network with the binary cross-entropy loss for one step of gradient descent. Initialize all the bias entries to be 0 and all the weight entries to be 1. Use learning rate α = 0.1
model = keras.Sequential([keras.layers.Dense(1,input_shape =(2,), activation="sigmoid", kernel_initializer='ones', bias_initializer="zeros")])
# Compile with a learning rate
learning_rate = 0.1  # Set your learning rate here
optimizer = Adam(learning_rate=learning_rate)  # Define optimizer with learning rate
model.compile(optimizer=optimizer,
              loss = "binary_crossentropy",
              metrics = ["accuracy"]
              )
model.fit(x_train,y_train, epochs=1)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 485ms/step - accuracy: 1.0000 - loss: 0.2201


In [33]:
coef, intercept = model.get_weights()
coef, intercept

(array([[0.9000214],
        [1.0999981]], dtype=float32),
 array([-0.09999511], dtype=float32))

# Now here is the implementation from `skratch` without using tensorflow

In [34]:
# Defining the sigmoid function
def sigmoid(x):
  return 1/(1+np.exp(-x))
sigmoid(-3)

0.04742587317756678

In [36]:
def predict_funct(x1, x2):
  weighted_sum = coef[0]*x1+coef[1]*x2+intercept
  return sigmoid(weighted_sum)

In [37]:
predict_funct(1,-2)

array([0.19782086], dtype=float32)

# Implementing the gradinet descent along with its helper functions

In [38]:
def log_loss(y_true, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [47]:
def gradient_descent(x1, x2, y_train, epochs):
  #w1, w2, b
  w1 = w2 = 1
  bias = 0
  lr = 0.1

  n = len(x1)

  for i in range(epochs):
    weighted_sum = w1*x1 + w2*x2 +bias
    y_predicted = sigmoid(weighted_sum)

    loss = log_loss(y_train, y_predicted)

    w1d = 1/n*np.dot(np.transpose(x1),(y_predicted-y_train))
    w2d = 1/n*np.dot(np.transpose(x2),(y_predicted-y_train))

    biasd = np.mean(y_predicted-y_train)

    w1 = w1 - lr*w1d
    w2 = w2 - lr*w2d

    bias = bias - lr*biasd

    print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss: {loss}')
  return w1, w2, bias

In [41]:
x_train.dtypes, y_train.dtypes

(x1    int64
 x2    int64
 dtype: object,
 labels    int64
 dtype: object)

In [42]:
x1 = df['x1'].values
x2 = df['x2'].values
y_train = df['labels'].values


In [44]:
gradient_descent(x1,x2, y_train, 1)

Epoch:0, w1:0.9984732211337121, w2:1.0268941421369995, bias:-0.0074869249673938714, loss: 0.22009484928059772


(0.9984732211337121, 1.0268941421369995, -0.0074869249673938714)

# Implementing the NN from scratch


In [50]:
class NN:
  def __init__(self):
    self.w1 = 1
    self.w2 = 2

    self.bias = 0

  def fit(self, X, y, epochs):
    self.w1, self.w2, self.bias = self.gradient_descent(X['x1'], X['x2'],y_train, epochs)

  def gradient_descent(self,x1, x2, y_train, epochs):
    #w1, w2, b
    w1 = w2 = 1
    bias = 0
    lr = 0.1

    n = len(x1)

    for i in range(epochs):
      weighted_sum = w1*x1 + w2*x2 +bias
      y_predicted = sigmoid(weighted_sum)

      loss = log_loss(y_train, y_predicted)

      w1d = 1/n*np.dot(np.transpose(x1),(y_predicted-y_train))
      w2d = 1/n*np.dot(np.transpose(x2),(y_predicted-y_train))

      biasd = np.mean(y_predicted-y_train)

      w1 = w1 - lr*w1d
      w2 = w2 - lr*w2d

      bias = bias - lr*biasd

      print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss: {loss}')
    return w1, w2, bias


In [51]:
my_model = NN()
my_model.fit(x_train, y_train, epochs=1)

Epoch:0, w1:0.9984732211337121, w2:1.0268941421369995, bias:-0.0074869249673938714, loss: 0.22009484928059772
